### ISSUE TITLE
If OLED off when unchecking Sleep when Inactive, it stays off

### ISSUE THREAD

**Issue by eovnu87435ds** [t3knomanzer/maxmix-software#108]
**Describe the bug**

I just recently upgraded to firmware 1.0.0 and application 1.0.0.0. If you uncheck "sleep when inactive" but the display is already asleep, the oled stays off, and volume controls do not work.

As a workaround, if I want the oled to stay always-on, I need to check "sleep when active," move the dial to wake it up, and then un-check it while the display is on. It then works as expected. 

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64

**Comment by t3knomanzer** [comment]
Good catch, thank you!
