### ISSUE TITLE
Desktop software CPU usage

### ISSUE THREAD

**Issue by ItsLemmy** [t3knomanzer/maxmix-software#110]
**Describe the bug**
MaxMix desktop software is constantly using about 16% of my i7-4790K CPU.

**To Reproduce**
1. Launch MaxMix 1.0 without any MaxMix device connected.
2. Launch Windows TaskManager.
3. Check CPU usage for MaxMix software in the TaskManager.

**Expected behavior**
Desktop software should use less CPU. 

**Screenshots**
![Taskmgr_833e5AI5PA](https://user-images.githubusercontent.com/2170677/89538371-7683c680-d7c8-11ea-8001-038f2c975d5c.png)

**Desktop :**
 - OS: Windows 10 Pro.
 - Version: 19.09

**Additional context**
Have not inspected the code yet, but I suppose the software is sending handshake too often ?

**Comment by t3knomanzer** [comment]
That's weird, I can't repro it. It peaks at ~7% when it connects but 99% of the time is at 0%.
I have an i9-9900K though. 
Can you repro it 100% of the time and what are your machine specs?
![Capture](https://user-images.githubusercontent.com/2942293/89592287-13625600-d801-11ea-95d6-eec8ebc2134e.JPG)

**Comment by t3knomanzer** [comment]
It's also interesting that it's using 37.6MB. With it running and with 5 applications open playing sound mine stays around 25MB

**Comment by SchemingWeasels** [comment]
i5-4690k 4.6GHz 16GB ram, Win 10 Home x64.
I see it go as high as 40%. I have 4 applications opened when taking this screenshot.
![image](https://user-images.githubusercontent.com/5172036/89611420-bf627a80-d8af-11ea-85c2-8aa7be7de374.png)

**Comment by t3knomanzer** [comment]
Ok. To be clear the repro steps are to just launch maxmix without the controller plugged in?   
I’ve tried that and also launching it, plugging in the controller, opening up a few apps, disconnecting the controller.   
Am I missing something?  
I will profile it regardless but I’d love to reproduce it.   
I’ll try on a different computer tomorrow also.

**Comment by SchemingWeasels** [comment]
> Ok. To be clear the repro steps are to just launch maxmix without the controller plugged in?

Yup. Drops to 0% once it's plugged in. I do have a COM1 device that is always connected to my system. I have no idea what driver/device is it referring to (just windows things~), but my speculation is that it could be polling that device which is not a MaxMix.

**Comment by t3knomanzer** [comment]
Huh, that’s a good point. I’ll try to connect another serial device to see if I can reproduce it. 

Thanks!

Ruben Henares

**Comment by ItsLemmy** [comment]
Yes, the repro steps are exactly as described (no device attached)
The behavior is consistent on my machine. 100% reproducible.

Like @SchemingWeasels I have a default COM1 available. I tried disabling it, then rebooted.
After that MaxMix is back to normal (< 1% CPU).

At least we know what is happening :)

I believe the COM1 device we see is the old school PS/2 port for mice and keyboard that can be found on older mother boards.

**Comment by t3knomanzer** [comment]
Oh nice! Cool you were able to narrow it down some more.   
Ok great, I should be able to repro it hopefully. 

Ruben Henares

**Comment by t3knomanzer** [comment]
Test

**Comment by t3knomanzer** [comment]
Testing discord integration.
