### ISSUE TITLE
CobsSerialization null exception

### ISSUE THREAD

**Issue by t3knomanzer** [t3knomanzer/maxmix-software#115]
**Describe the bug**
In certain situations, deserialization of messages can fail. Currently exceptions are being raised but not caught and that's causing silent crashes.

**Expected behavior**
Exceptions should be handled gracefully.

**Screenshots**

**Desktop (please complete the following information):**
 - Version: [e.g 10 x64]

**Additional context**

**Comment by t3knomanzer** [comment]
There is a new pre-release version (1.0.3) compiled here with the fixes:
Let me know if it fixes the application crashing:
https://github.com/t3knomanzer/maxmix-software/releases/tag/1.0.3

**Comment by rantanlan** [comment]
Just tried with 1.0.3 still crashing...

**Comment by t3knomanzer** [comment]
Ok. The good news is that now we have automatic crash reporting so I can see the crash :D yey!
I found the issue, an oversight on my side. I think it should be fixed now. I'll push a new version in a few and let you know.

**Comment by t3knomanzer** [comment]
1.0.4 pre-release is out. Let me know if it fixes it this time.
https://github.com/t3knomanzer/maxmix-software/releases/tag/1.0.4

**Comment by rantanlan** [comment]
Tested again.. but somehow now my device seems to reconnect and disconnect every 2-3 seconds while using it ... and crashed again after some time.

**Comment by t3knomanzer** [comment]
Yeah that’s going to be your arduino or your cable for sure at this point. 

I can see the crash and it’s low level communication stuff. There are other users utilizing the usb-c version without issues. 

Going to close the bug and I would suggest that you ask in our subreddit if that’s ok.

**Comment by rantanlan** [comment]
It's no problem I already suspected this this to be faulty. I just use the other arduino with mini usb.. little more soldering to do. Thanks for your time and patience!
