### ISSUE TITLE
Spotify is missing from controllable apps since 1.0.2

### ISSUE THREAD

**Issue by TheFoxBurrow** [t3knomanzer/maxmix-software#118]
**Describe the bug**
Spotify is missing in the applications to control the volume for.

**To Reproduce**
I updated to 1.0.2, and it just doesn't show up anymore, as if it doesn't recognize it as an audio source.

**Expected behavior**
Well I kinda expected Spotify to still be there.

**Desktop (please complete the following information):**
Windows 10 pro for Workstations, Version 1909, Build 18363.959

I know Spotify was sometimes problematic, showing up in Maxmix as the name of the song that was played when Maxmix was launched and leading to crashes sometimes, but straight up removing seems like a very Apple way to handling that bug :)

**Comment by t3knomanzer** [comment]
Hey,

I'm not able to repro this at all. Spotify still working just like before on my side.  
Spotify has always worked fine for me, in fact is my something I use all day long.  
The only thing to be aware with spotify is that it will only appear in the device after you have pressed play in the app. That is the same behavior seen in windows mixer though.  

Can you double-check and confirm that you can reproduce this 100%?

**Comment by TheFoxBurrow** [comment]
I could reproduce it, but after several un- and reinstalls it seems to have fixed itself. It was very weird to me as well, since spotify showed up in the windows mixer, but not in maxmix. I'll keep an eye out should  the issue ever reappear.
