### ISSUE TITLE
Make acceleration customizable

### ISSUE THREAD

**Issue by t3knomanzer** [t3knomanzer/maxmix-software#122]
**Is your feature request related to a problem? Please describe.**
With a wide range of rotaries being used by users, acceleration values may not be ok for all of them. 

**Describe the solution you'd like**
I would like to be able to fine tune  the acceleration value from the desktop app.

**Describe alternatives you've considered**

**Additional context**

**Comment by SchemingWeasels** [comment]
I could transfer over my exponential acceleration stuff for this one. Only one value is needed to adjust the acceleration.

**Comment by ItsLemmy** [comment]
Sounds good. That being said I'm going to wait a bit until we got a solution for the encoder.
