### ISSUE TITLE
Implement basic lighting FX

### ISSUE THREAD

**Issue by t3knomanzer** [t3knomanzer/maxmix-software#129]
**Guidelines**
- [X] I have reviewed the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

**Is your feature request related to a problem? Please describe.**
The RGB light ring is a powerful way of providing visual feedback and it's not being utilized.

**Describe the solution you'd like**
I would like to see some basic light effects implemented such as pulse, chase, etc. to provide visual feedback to user input or state.  
Things that come to mind for example:
Turn the LEDs red and pulse when mute is on.  
In game mode, pulse the left LED when selecting channel A and the right one when selecting B.

**Describe alternatives you've considered**
NA

**Additional context**
We need to be mindful of power usage.
Each LED channel is 20mA, full brightness white is 60mA.   
The ring has 8x60ma=480mA.  
The 5v pin should provide the full USB current when powered via USB ~500mA but let's say ~480mA to be on the safe side.
From that we need so subtract the current for the arduino and the OLED.  
I'd say at max we should count on 6 LEDs at full brightness or limit the brighness to 75% for a total of 360mA.

**Comment by ItsLemmy** [comment]
Great idea.  I have yet to receive the led ring from aliexpress, so I could not check the existing effects and could not really tell what was going on from the video.

From my experience with SMD leds (I've been doing lights show with thousands of them for years), I would suggest to simply limit the brightness of all the leds (ie. using NeoPixel::setBrightness) this would limit the power usage, avoid the leds getting too hot and most importantly preserve the led's lifetime.  I believe around 60% would be perfect for our use case.

I would be glad to take a stab at it once I got the led ring delivered. If it takes too long I can cut 8 pixels from some left overs 2812 strips I have laying around...

**Comment by t3knomanzer** [comment]
@quadbyte it's awesome to have someone with your experience here!
If it takes too long and you want to get started, let me know and I'll order you one on Amazon.

**Comment by ItsLemmy** [comment]
Still waiting on the led ring, it seems they are also sold out on amazon, or at least it looks like it would come from China too...

**Comment by t3knomanzer** [comment]
Oh no! I have a bunch here, if you email me your address I’m happy to send you one.

**Comment by ItsLemmy** [comment]
Thank you so much, I sent my address via the website's contact form.

**Comment by t3knomanzer** [comment]
You’re welcome! I’ll send it out ASAP!
