### ISSUE TITLE
Optimize volume acceleration calculation

### ISSUE THREAD

**Issue by t3knomanzer** [t3knomanzer/maxmix-software#130]
**Guidelines**
- [X] I have reviewed the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

**Is your feature request related to a problem? Please describe.**
The volume acceleration calculation uses floating point numbers which is expensive to run on an atmega328

**Describe the solution you'd like**
Optimze calculations to use integers.

**Describe alternatives you've considered**

**Additional context**

**Comment by ItsLemmy** [comment]
I wrote a little something which work fine using fixed points math, using this library.
https://github.com/Pharap/FixedPointsArduino

Will create a PR soon.
