### ISSUE TITLE
Mic Inputs

### ISSUE THREAD

**Issue by logicl77** [t3knomanzer/maxmix-software#138]
**Guidelines**
- [X ] I have reviewed the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

**Is your feature request related to a problem? Please describe.**
Add microphone inputs to the list of available items to control and mute

**Describe the solution you'd like**
be able to see the microphone with the menus

**Describe alternatives you've considered**

**Additional context**

**Comment by chris-guthrie** [comment]
Came here looking to see if that was already talked about, I think this could be a nice feature. No idea how hard it would be to implement.

**Comment by t3knomanzer** [comment]
Definitely on the list! 
We are going to be releasing output device switching and volume control in the next release 1.2.0. We’ll be looking into output mode right after that.
