### ISSUE TITLE
Changing volume quickly using half-step crashes host software

### ISSUE THREAD

**Issue by MxBlu** [t3knomanzer/maxmix-software#147]
**Guidelines**
- [x] I have reviewed the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

**Describe the bug**
When using 1.1.1 Half-step firmware, changing the volume quickly can cause the host firmware. Couldn't reproduce the same on the standard 1.1.1 firmware.

**To Reproduce**
1. Plug in Maxmix
2. Wait for connected alert
3. Quickly max volume
4. Quickly min volume (if not already crashed)
5. Check app, likely has crashed, If not, repeat 3/4.

**Expected behavior**
App should not crash.

**System information:**
 - OS version: Win 10 Pro x64 Version 10.0.19042 Build 19042
 - Firmware version: 1.1.1 Half-step

**Comment by SchemingWeasels** [comment]
~~Does the MaxMix constrain properly to 0/100? Eg. Step 3, does the OLED show 100? and step 4 show 0?~~

Edit: Also, update to 1.1.2 and try again. Report back if it's still happening

**Comment by t3knomanzer** [comment]
@MxBlu Can you confirm if it still happens in 1.1.2?

**Comment by MxBlu** [comment]
It did indeed constrain correctly to 0 =< vol <= 100.

Installed 1.1.3 and reflashed half-step, looks like it's working well! I'll reopen the issue if I run into it again.

Thanks!
