### ISSUE TITLE
Application settings not kept between updates

### ISSUE THREAD

**Issue by t3knomanzer** [t3knomanzer/maxmix-software#155]
**Guidelines**
- [X] I have reviewed the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

**Describe the bug**
User settings are not being maintained between application updates

**To Reproduce**
1. Install a version
2. Run the app and change the settings'
3. Update to a newer version
4. Run the app and observe how the settings are reset to default.

**Expected behavior**
User changed settings should be maintained between application updates.

**Screenshots**

**System information:**
 - OS version: [e.g. Windows 10 x64 1008]
 - Firmware version: [e.g 1.0.4]

**Additional context**
https://docs.microsoft.com/en-us/dotnet/desktop/winforms/advanced/application-settings-overview?view=netframeworkdesktop-4.8

**Comment by samgaudr** [comment]
@t3knomanzer, can I give a shot at this issue?

**Comment by ItsLemmy** [comment]
@samgaudr , any help is welcomed, feel free to contribute with PR ! Thanks
