### ISSUE TITLE
Double-tap is not very responsive

### ISSUE THREAD

**Issue by t3knomanzer** [t3knomanzer/maxmix-software#178]
**Guidelines**
- [X] I have reviewed the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

**Describe the bug**
Double-tap doesn't seem to behave as well as it should. It feels laggy and sometimes misses.

**To Reproduce**
1. Just double tap to mute/unmute anything multiple times
2. Observe how sometimes it misses.

**Expected behavior**
To be more responsive and respond better to the timing settings in the application.

**System information:**
 - OS version: Windows 10 x64
 - Firmware version: 1.2.0

**Additional context**

**Comment by t3knomanzer** [comment]
@SchemingWeasels Would you like to take this one?

**Comment by SchemingWeasels** [comment]
Sure. The simplest idea I have is to call encoderButton.update() in the timer isr. I'll give it a test today.
