### ISSUE TITLE
When I turn the button too fast, it disconnects from the application.

### ISSUE THREAD

**Issue by edyman01** [t3knomanzer/maxmix-software#193]
**Guidelines**
- [x] I have reviewed the [guidelines for contributing](https://github.com/t3knomanzer/maxmix-software/blob/master/.github/CONTRIBUTING.md) to this repository.

**Describe the bug**
When I turn the button too fast, it disconnects from the application and does not connect automatically until I remove the cable from the usb. When I do this the desktop application conflicts with another arduino board that I have connected to the pc (it would be useful an option through which you can choose exactly the usb port to check if there is maxmix).

**To Reproduce**

**Expected behavior**
Do not disconnect as fast as the button wheel or at least connect immediately after.

**Screenshots**

**System information:**
 - OS version: Windows 10 x64 19041.508
 - Firmware version: 1.2.1.0

**Additional context**

**Comment by t3knomanzer** [comment]
Hey,

Would you mind providing step by step instructions to reproduce the bug?   
Also what’s in the other arduino board that’s connected?   
Other COM peripherals, regardless of what they are should not conflict with maxmix, since the application expects a specific handshake from the device.

**Comment by edyman01** [comment]
Hi! I'll make a video when I get home. I leave the link below from the
other project that uses an arduino pro micro board. It conflicts with that
board right after installation when it tried to communicate with the maxmix
board and gave errors. But this is not so serious, just put a warning for
future users that installation errors may occur if they have other projects
with arduino connected to the pc.

https://www.instructables.com/id/Windows-PC-LockUnlock-Using-RFID/

În lun., 14 sept. 2020 la 02:52, Ruben Henares <notifications@github.com> a
scris:

**Comment by edyman01** [comment]
https://we.tl/t-RMCyS4CErQ

Video with the bug. The problem does not always appear the same, sometimes
it appears much faster. It is noticed when I remove the maxmix USB cable,
it stops and the LED on the other board starts flashing.

În lun., 14 sept. 2020 la 02:52, Ruben Henares <notifications@github.com> a
scris:

**Comment by t3knomanzer** [comment]
Awesome, thanks for recording it. Let’s see if we can reproduce it and fix it. 

Thanks! 

Ruben Henares

**Comment by edyman01** [comment]
No problem!
