### ISSUE TITLE
Start with Windows

### ISSUE THREAD

**Issue by maelremrem** [t3knomanzer/maxmix-software#194]
**Guidelines**
- [x] I have reviewed the [guidelines for contributing](https://github.com/t3knomanzer/maxmix-software/blob/master/.github/CONTRIBUTING.md) to this repository.

**Is your feature request related to a problem? Please describe.**
Yes, It would be better if the computer app start with windows.

**Describe the solution you'd like**
Add a start with windows option (as well as in the installer)

**Comment by Mavi222** [comment]
It would be nice to have a simple checkbox, yeah.

In the meantime, you can add shortcut to "shell:common startup" folder
(press WIN+R, into the window, paste "shell:common startup" without quotation marks, press enter, it will open a folder where you can paste a shortcut of the Maxmix.)
"shell:common startup" for all users on the computer
"shell:startup" just for currently logged user.

**Comment by pbanj** [comment]
i have mine set like this atm and have found the maxmix software doesnt connect unless i replug or use the reset button i installed on my maxmix.

**Comment by Mavi222** [comment]
Weird, I don't have that problem pbanj.

**Comment by pbanj** [comment]
i thought the arduino was just turning off as it wouldnt react. but with the beta the led ring just keeps spinning like it is waiting for the software to connect. for me it isnt really an issue as i installed a reset button, but it is something to keep in mind
