### ISSUE TITLE
Add option to select the sense of rotation

### ISSUE THREAD

**Issue by maelremrem** [t3knomanzer/maxmix-software#196]
**Guidelines**
- [x] I have reviewed the [guidelines for contributing](https://github.com/t3knomanzer/maxmix-software/blob/master/.github/CONTRIBUTING.md) to this repository.

**Is your feature request related to a problem? Please describe.**
Sometime, the encoders that came form the same vendors are working in the opposite direction.

**Describe the solution you'd like**
A nice option would be to have a setting on the pc app to select/invert the direction of the encoder

**Comment by SchemingWeasels** [comment]
Duplicate of #192.
