### ISSUE TITLE
Volume on Teams meeting doesn't change

### ISSUE THREAD

**Issue by Forgenn** [t3knomanzer/maxmix-software#219]
**Guidelines**
- [x] I have reviewed the [guidelines for contributing](https://github.com/t3knomanzer/maxmix-software/blob/master/.github/CONTRIBUTING.md) to this repository.

**Describe the bug**
When selecting Teams on the device, turning the encoder doesn't modify the volume of the meeting.

**To Reproduce**
1. Open Teams
2. Enter a meeting
3. Try to modify the volume with the device
4. It won't work

**Expected behavior**
The volume should change.

**System information:**
 - OS version: Windows 10 LTSC
 - Firmware version: 1.3.1.0

**Additional context**
It seems Teams opens a new audio channel when opening a meeting, but the sound of that meeting is still
controlled in the main Teams windows. When selecting the application in the device, only the window of the meeting appears,
which can't change the volume of the meeting, a bit confusing. The device should show both of the channels.

![Capture](https://user-images.githubusercontent.com/35640780/95326488-f995cb80-08a2-11eb-8c74-4ab1c4bc98aa.PNG)

The channel that the device controls is the left one, but the right one is the window that outputs the sound, which doesn't appear. I don't know if this is a problem with Teams or the maxmix software.

**Comment by pbanj** [comment]
I've noticed this with discord lately. Rebooting the maxmix and software fixed it every time.

**Comment by Forgenn** [comment]
> I've noticed this with discord lately. Rebooting the maxmix and software fixed it every time.

I tried your fix but it didn't work, I think it's a different type of bug, because the problem here is that the maxmix doesn't 
show the channel where the output is.

**Comment by pbanj** [comment]
discord is doing the same thing but im not even in a chat with it. so seems it is the same issue but i was getting lucky on restarting the app and maxmix. 
![image](https://user-images.githubusercontent.com/17306233/95507758-e4db3580-097f-11eb-8ddb-a9f3b0186ebe.png)

**Comment by Forgenn** [comment]
Oh I see, it's the same problem then. Reconnecting the maxmix when inside a meeting has fixed it as you said before, but it looks like its doesn't work all the time for me. Thanks for your help.

**Comment by XScorpion2** [comment]
should be fixed in 1.4.2 beta

**Comment by Forgenn** [comment]
> should be fixed in 1.4.2 beta

At the moment installing the new 1.4.2 pre-release doesn't work for me, I have to revert to 1.3.2, so I can't check it. Should I close the issue anyways?

**Comment by Forgenn** [comment]
Fixed with version 1.4.3.
