### ISSUE TITLE
Text not masked correctly in mix mode

### ISSUE THREAD

**Issue by t3knomanzer** [t3knomanzer/maxmix-software#222]
**Guidelines**
- [X] I have reviewed the [guidelines for contributing](https://github.com/t3knomanzer/maxmix-software/blob/master/.github/CONTRIBUTING.md) to this repository.

**Describe the bug**
In mix mode, text scrolling can be seen under the volume bars.

**To Reproduce**
1. Go to mix mode
2. Select 2 applications that have names long enough to not fit in the edit screen.
3. Leave it until the text starts scrolling.
4. See how the text can be seen under the volume bar.

**Expected behavior**
Text should be masked properly.

**Screenshots**

**System information:**
 - OS version: Windowx 10 x64
 - Firmware version: 1.4.1

**Additional context**

**Comment by XScorpion2** [comment]
Interesting, this is an old bug then as the clearing of text behind the volume bar has been unchanged since original implementation.
