### ISSUE TITLE
The Maxmix display shows weird second line when showing certain app names.

### ISSUE THREAD

**Issue by Mavi222** [t3knomanzer/maxmix-software#237]
**Guidelines**
- [X] I have reviewed the [guidelines for contributing](https://github.com/t3knomanzer/maxmix-software/blob/master/.github/CONTRIBUTING.md) to this repository.

**Describe the bug**
The Maxmix shows second row of text when for example Call of Duty Warzone is selected.

**To Reproduce**
1. Open Warzone
2. Change Maxmix to game mode
3. Scroll to Warzone

**Expected behavior**
No second line of text on display

**Videos**
https://youtu.be/MTsUsSTdygU
https://youtu.be/Oj5g0vKfSX8

**System information:**
 - OS version: Windows 10 Pro x64 20H2
 - Firmware version: 1.4.7.0

**Comment by acekrystal** [comment]
Is this still a problem? I tested this and for me it seems to work fine. Warzone is scrolling on a single line.

**Comment by ItsLemmy** [comment]
Closing this, it's a known issue which happens when the Arduino runs out of memory in previous firmware versions.
