### ISSUE TITLE
Device Hard Reset Required on USB Connection

### ISSUE THREAD

**Issue by pearson** [t3knomanzer/maxmix-software#239]
**Describe the bug**
When plugged into USB, the device displays the "MAXMIX" logo, but does not seem to communicate with the desktop software. The icon in the Windows icon tray remains grey. Pressing the reset button on the hardware leads to a successful connection.

**To Reproduce**
1. Desktop software is running and the icon tray icon is grey.
2. The hardware is plugged into USB.
3. The hardware display will show the "MAXMIX" logo indefinitely and the Windows icon tray icon will remain grey.
4. Press the reset button on the hardware.
5. The hardware will reset, the "MAXMIX" logo will display briefly, and the device will begin to operate as expected.

**Expected behavior**
I would expect the hardware to connect on the initial plug in.

**System information:**
 - Hardware is an Elegoo Nano v3, which uses the ATmega328P and the CH340 USB to serial chip.
 - There is no LED ring attached yet, should that be an issue. (Delivery of my LED ring has been delayed.)
 - I'm using the release 1.4.7 software / firmware.

**Additional context**
My background is software but I lack familiarity with Windows drivers, so personally debugging this issue may take some time. Unless someone has a suggestion as to where to look for a problem here, I may start with the device firmware and place a timeout / reset when it is showing the startup logo.

**Comment by acekrystal** [comment]
What does it do on startup of your system? Does it also not connect on startup?

A potential fix might be setting the baud rate from 115600 to 76800.  For me this fixed random mute/un-mute and random volume jumps. But also the amount of disconnects used to have. Till now I have had 0 disconnects.
Also using an ATmega328P with CH340(c) (Ardnuino Nano USB-C).

I made a pull request for this change also might you be interested : [](https://github.com/t3knomanzer/maxmix-software/pull/250)

Let me know if I can help ya, I have already a build Maxmix.exe with the baud changed, if you wish to test it I can send ya a download link.

**Comment by pearson** [comment]
Thanks for the reply, @acekrystal . I should have closed this issue a while back. I don't know what changed, but that issue no longer appears. Other than a few crashes, it has been running quite well since then. (I had thought this project might be abandoned, given the age of the last changes, so I hadn't bothered posting any other issues.)

It seems like you forgot to include your PR. 😃 

I'm interested in working on this project, if it's still active.

**Comment by acekrystal** [comment]
@pearson I'm exited to do some stuff in this project too ;)
I see I forgot the PR indeed, its pretty small but here ya go , the Baud rate change : https://github.com/t3knomanzer/maxmix-software/pull/250
