### ISSUE TITLE
Friendly Name/Nickname of Input/Output devices.

### ISSUE THREAD

**Issue by ThisIsRinesi** [t3knomanzer/maxmix-software#241]
**Guidelines**
- [x] I have reviewed the [guidelines for contributing](https://github.com/t3knomanzer/maxmix-software/blob/master/.github/CONTRIBUTING.md) to this repository.

**Is your feature request related to a problem? Please describe.**
Selecting your input/output devices should show the friendly names you have assigned in Windows. Currently I have names for all of my devices assigned, but the Maxmix shows their actual names (Headphones show as "Nvidia" instead of "Headphones")

**Describe the solution you'd like**
Default to Friendly Names/ make it an option in settings.

**Comment by ZeddBlock** [comment]
It would be a very nice feature ! Because I'm quite lost with all default names hehe.
