### ISSUE TITLE
Master volume mode

### ISSUE THREAD

**Issue by t3knomanzer** [t3knomanzer/maxmix-software#40]
**Is your feature request related to a problem? Please describe.**
From Reddit:

*Great project! Two ideas that came to my mind:*
- *Could the standard mode for turning be the system volume, and only when you press the button you choose an individual application?*
- *Maybe one could add a row of 3 or 4 macro keys to this. To directly start or choose an application.*

https://www.reddit.com/r/functionalprint/comments/hiyqmz/introducing_maxmix_an_opensource_volume_mixer_for/fwkcmwb?utm_source=share&utm_medium=web2x

**Describe the solution you'd like**
[ ] Implement the concept of MODES in the firmware. 
    Switch modes by holding the button down.
[ ] Implement master volume control as the default mode.
[ ] Make app volume control into a mode.

**Describe alternatives you've considered**
NA

**Additional context**

**Comment by Mavi222** [comment]
I would like to have a different controls.

- **Just turning**: Master volume level

- **Short press**: After short press, switch between applications by turning the knob, press again to control the volume of the selected application.

- **Long press**: After long press, switch between audio output devices by turning the knob, press again to choose the output device.

But in my country there's saying "100 people, 100 tastes", and I am sure that not all the people would like these controls. Best way to fight this would be if we could have a settings app, where you could choose what just turning, short pressing and long pressing would do.

**Comment by t3knomanzer** [comment]
I've ended up adding "Master" as if it was another application instead of creating a separate mode just for it.

If you scroll to it and press the knob to edit the volume and leave it there, it'd be the same as having a separate mode where you just control the master volume by turning the knob.
