### ISSUE TITLE
Installer Crash

### ISSUE THREAD

**Issue by Nick737373** [t3knomanzer/maxmix-software#44]
Whenever I try to install this, it says "There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor." Vaguely reading through the log, it seems to be an issue with the driver installer.

**Comment by t3knomanzer** [comment]
Oh, I just fixed that issue this afternoon and published a new version. I must have forgotten to update the link on the website.
Can you try version 0.10.1?
https://github.com/t3knomanzer/maxmix-software/releases/tag/0.10.1

**Comment by Nick737373** [comment]
That one works! I think it was just that 0.10.1 isn't the website link.

**Comment by t3knomanzer** [comment]
Yep. I just fixed the link on the website. Thanks for reporting it!
