### ISSUE TITLE
I've got an entry '@%SystemR'

### ISSUE THREAD

**Issue by tocklime** [t3knomanzer/maxmix-software#55]
**Describe the bug**
After installing the current prerelease (I think I might have seen it before too, I'm not sure). I have an item whose volume I can control with the device called '@%SystemR' / '@%SystemRoot%/Syst'. I can move the volume up and down with the device, but can't see it having any effect in windows volume mixer.

Having unplugged and re-plugged the device, it has gone away.

**To Reproduce**
Observed once - is there any logging I can look at in case it happens again?

**Expected behavior**
I expect the list on the device to match the list currently in windows volume mixer.

**Comment by t3knomanzer** [comment]
So I've decided to rollback the changes for now. Apparently the CSCore API does not have a way of getting the exact same name that the windows mixer shows so I will have to look for a better solution but it will involve more work.

Can you confirm that this but also happens in 10.2?

**Comment by tocklime** [comment]
Reproduced in v0.10.2 - it's system sounds. For instance, if I open up sound control panel and press the test speaker button, it makes the test sound. Changing the volume of @%SystemRoot%/Syst makes that test sound louder and quieter.

Having said that, it's not reliably doing it. I can't find a unplug/restart maxmix.exe sequence that makes it happen reliably.

Maybe you're filtering out 'System Sounds', but sometimes it comes up with the weird name and doesn't get filtered?

Are there any log files?

**Comment by t3knomanzer** [comment]
There aren't any log files. When  I get the list of active audio sessions, they have a property called IsSystemSoundSession. If true I ignore it.  
My guess is that for some reason that property is false sometimes when it should be true.  

I will add an extra check to look for "SystemRoot" in the name of the session.

Thanks for reporting it!

**Comment by t3knomanzer** [comment]
@tocklime This also has very likely been fixed by PR #70.   
Could you verify?  

Thank you!

**Comment by tocklime** [comment]
Yep, it looks like the changes in #70 stop this happening.
