### ISSUE TITLE
installer/uninstaller fails to kill maxmix.exe

### ISSUE THREAD

**Issue by tocklime** [t3knomanzer/maxmix-software#56]
When installing update/uninstalling, the installer offers to stop processes which are running. You say ok, and then it thinks for a bit and decides it can't stop all the processes. In Task Manager, i see a maxmix.exe. I kill it, and then the uninstall proceeds OK.

Ideally it would suceessfully stop the running process during uninstall.

**Comment by t3knomanzer** [comment]
Good catch!  
I'll take a look at the installer to see if there is anything not setup properly. It may be a bug of AdvancedInstaller itself.

Thanks!
