### ISSUE TITLE
installer requires internet access.

### ISSUE THREAD

**Issue by tocklime** [t3knomanzer/maxmix-software#57]
**Describe the bug**
Whilst installing a new version, I got a message saying that the installer requires internet access to continue. I was connected to the internet, but also to my work VPN (via openvpn). Some programs believe that the internet isn't connected when that VPN is up (spotify is the most annoying one), but firefox and most other programs work fine. I disconnected the VPN and the install went through fine.

**To Reproduce**
1. Connect OpenVPN
2. install maxmix

**Expected behavior**
tbh, I wasn't expecting it to require internet access. If it really does, then fine, I'll add it to my mental list of programs which don't work with the VPN up, but it'd be nice if it didn't do this network connection check (which returns false results on my PC)

**Desktop (please complete the following information):**
 - OS: Windows 10 20.04

**Comment by t3knomanzer** [comment]
So the only reason internet access is required is because it downloads dependencies (.net framework) automatically for you if missing. 

I will check to see if there is any other way we can do it or report the bug to AdvancedInstaller for them to fix.

Thank you!
