### ISSUE TITLE
 Return to STATE_APPLICATION_NAVIGATE on MSG_COMMAND_REMOVE

### ISSUE THREAD

**Issue by SchemingWeasels** [t3knomanzer/maxmix-software#68]
**Is your feature request related to a problem? Please describe.**
It's annoying when I close an application that is currently selected in edit mode and it remains in edit mode.
The screen goes to sleep and you just forget that it's still in edit mode. So when you go and move the knob to wake the device, it edits the volume of some other application now, since the previously closed one is now removed.

I then need to put the volume back to what it was, exit edit mode, find the new application I wanna change, and then go change it.

**Describe the solution you'd like**
Either one of these is fine, I'm undecided which is better. Could use some feedback.
1. Return to STATE_APPLICATION_NAVIGATE if the selected application is closed.
2. Return to STATE_APPLICATION_NAVIGATE after x-time of inactivity
3. Return to STATE_APPLICATION_NAVIGATE on SLEEP
3. Initial input from SLEEP state, aka "onWake", the first input is discarded (only used to wake device).

**Describe alternatives you've considered**
Refer to the section above

**Additional comments**
Add a choice to the Desktop application? I don't think it's necessary. Depends on what 'normal behavior' should be.

**Comment by SchemingWeasels** [comment]
I'm testing a few of the solutions now. I'll give some feedback on which I find to be most intuitive.

**Comment by SchemingWeasels** [comment]
I think 1 is the most intuitive. 
2 can get annoying if you are actively adjusting a particular application. For example, watching youtube videos which all have varying levels. 
3 is the same as 2.
4 additional keystrokes, especially noticeable if you're in the same situation as 2.

What do you think about implementing the same feature when a new app is added? Only switches to navigate if displayNewSession is set.

**Comment by t3knomanzer** [comment]
Agreed.   
I think that one makes complete sense.   
There is actually another issue for 4 #74 which I think it also makes sense.

**Comment by SchemingWeasels** [comment]
Yes, I just saw your issue. Working on it. Will combine into the same PR.
