### ISSUE TITLE
Group sessions from apps together into one volume control

### ISSUE THREAD

**Issue by XScorpion2** [t3knomanzer/maxmix-software#69]
I'm working on this improvement in my fork just as a heads up. Got all the code done and should have it integrated by this weekend.

**Comment by t3knomanzer** [comment]
Awesome, looking forward to it!
The next release is going to be packed!

Thanks.

**Comment by XScorpion2** [comment]
Oh and @t3knomanzer good job on the updated encoder handling, I was going to tackle that next =D
