### ISSUE TITLE
Update drawing code

### ISSUE THREAD

**Issue by t3knomanzer** [t3knomanzer/maxmix-software#73]
**Is your feature request related to a problem? Please describe.**
The application mode screen drawing code is quite messy and since it uses absolute positions it won't work
with other screen resolutions.

**Describe the solution you'd like**
Update it to follow the new game mode approach, using variables to calculate positions using relative coordinates.

**Describe alternatives you've considered**

**Additional context**

**Comment by SchemingWeasels** [comment]
I'll check it out. I have the larger 128x64 oled as well.

I think we could use the larger screen to display more information and elements but this should be for a much future release, after game mode and groupings #69.

My suggestion is I'll clean up the drawing first, followed by adding support for the larger oled without anything new.

**Comment by SchemingWeasels** [comment]
If we do percentages for screens it becomes scalable across multiple screen resolutions, but the code becomes messy. We'll be dealing with a lot of floating-point numbers which Arduinos kinda suck at. 

How about we keep the hardcoded pixel drawing, but we move the absolute pixel locations over to a separate header file, and use precompile directives to select the display type to compile for. After all, I'm guessing we would want to have different UI designs for different screen sizes.  What do you think?
