### ISSUE TITLE
#define HALF_STEP in maxmix.ino doesn't seem to work

### ISSUE THREAD

**Issue by relax81** [t3knomanzer/maxmix-software#77]
**Describe the bug**
When i use the 0.10.4 Firmware i always had to do two clicks on my ky-040 rotary encoder. To fix it I downloaded the current master and uncommented the 
`#define HALF_STEP`
directly in the library file (rotary.h line 11)

For some reason the 
`#define HALF_STEP`
 in the maxmix.ino seems to have no effect

 

**To Reproduce**
1. Use the current 0.10.4 firmware
2. rotate the knob. It will only count every second turn 

**Expected behavior**
It should change at every single turn

**Desktop (please complete the following information):**
 - OS: Windows 10 x64

**Comment by SchemingWeasels** [comment]
Could you link the rotary encoder you are using? Is it the same as the one in the build guide?

I'm having difficulty reproducing this.

**Comment by SchemingWeasels** [comment]
@t3knomanzer What version of Bounce2 is the pre-compiled binaries compiled on?
I can't reproduce this with Bounce2 2.53

Edit:  reproduced the issue. Didn't notice before due to the encoder I was using. Technically for the encoder in the build website, HALF_STEP should be turned OFF.

**Comment by SchemingWeasels** [comment]
Based on this thread on the Arduino forums, it seems like we'll have to include a modified library, or at least the header file Rotary.h. Then have users choose which firmware to flash (for precompiled bins) for their hardware.

https://forum.arduino.cc/index.php?topic=191906.0

**Comment by t3knomanzer** [comment]
Right... yeah we may have to modify the library and distribute it.
Alright, I'll assign a milestone to it so we can take a look later.

**Comment by relax81** [comment]
Thank you. WIth the current 0.15 update i had the same issue. Official firmware update = two turns necessary, with the self compiled one  (and change in the library) one turn. With the variety of ky-040 rotary encoders out there and not really knowing what we get from China i guess it's really the best if there would be some sort of option to pick before updating the firmware.

**Comment by t3knomanzer** [comment]
Right. Ok we’ll definitely have to think of something then for the next release. 
Thanks for reporting it, stay tuned!
