### ISSUE TITLE
Implement mute/unmute on double click in app mode

### ISSUE THREAD

**Issue by t3knomanzer** [t3knomanzer/maxmix-software#78]
**Is your feature request related to a problem? Please describe.**
The only way I currently have to stop the sound of an application is to reduce the volume to 0.

**Describe the solution you'd like**
I would like to be able to mute/unmute an application on double click when in app mode.

**Describe alternatives you've considered**
NA

**Additional context**

**Comment by SchemingWeasels** [comment]
Do you want the app to trigger the mute in the system, or just reduce the vol to zero, and restore it on unmute?

**Comment by t3knomanzer** [comment]
Trigger mute/unmute, that way the volume is restored. Most of the code for the app is already there, should be easy. 
This issue needs to wait though until #73 is completed since we will need a way to visualize on the screen that something is muted/unmuted.

**Comment by cs2000** [comment]
Looking at #93 Why not use a long press (2 seconds or something) for enabling/disabling mute mode, then double press can be used in #93

**Comment by SchemingWeasels** [comment]
> Looking at #93 Why not use a long press (2 seconds or something) for enabling/disabling mute mode, then double press can be used in #93

Long press is currently used for Game Mode (Balance mode)

**Comment by t3knomanzer** [comment]
So the idea is to keep the input behavior consistent. 
Long press to cycle between modes. 
Tap to cycle between states within a mode, I.e: In app mode, switch between selection, and volume adjustment. In game mode switch between channel a, channel b selection and volume adjustment.  
Double tap is a special action different for each mode. I.e: in game mode, it sets the volume of both apps to 50%. In app mode it controls mute/unmute. 

Currently there is just app mode and game mode but that list will grow.
