### ISSUE TITLE
Add message reception acknowledgement

### ISSUE THREAD

**Issue by t3knomanzer** [t3knomanzer/maxmix-software#81]
**Is your feature request related to a problem? Please describe.**
Currently there is an intentional delay on the application side after sending a message to give the device time to read it. This
causes communication to be pretty slow.

**Describe the solution you'd like**
Add a message received acknowledge system so that the next message can be sent as soon as reception of the previous one is confirmed.

**Describe alternatives you've considered**
NA

**Additional context**

**Comment by ItsLemmy** [comment]
I have something working !
Just need to clean things up a bit.
