### ISSUE TITLE
App names on device don't match windows mixer

### ISSUE THREAD

**Issue by t3knomanzer** [t3knomanzer/maxmix-software#86]
**Describe the bug**
The application names shown on the device screen don't match the ones in windows mixer. That can sometimes be confusing like in the case of Cisco Webex.

**To Reproduce**
1. Launch Cisco Webex
2. Start a call
3. Look at the names of the apps in the device
4. See how the name of the process is being used

Note: You can not create a meeting in webex as a guest so this is hard to verify. I do have access to a computer with
a webex corporate account so either myself or @tocklime can verify this.

**Expected behavior**
Names shown in the device should match those in windows mixer.

**Screenshots**
|system volume manager | on maxmix |
| ------------------------ | ---------- |
| Cisco Webex Service | Atmgr |
| Cisco Webex Meetings Desktop App | Ptoneclk |

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10 x64

**Additional context**

**Comment by XScorpion2** [comment]
Another application for testing this: 

system volume manager | on maxmix
------------ | -------------
Steam Client Bootstrapper | Steam
