### ISSUE TITLE
Implement master volume mode

### ISSUE THREAD

**Issue by t3knomanzer** [t3knomanzer/maxmix-software#93]
**Is your feature request related to a problem? Please describe.**
There isn't currently any mode to just control the master volume. Sure it can be done from application mode but I feel like it makes sense for it to be a separate mode.

**Describe the solution you'd like**
Have a dedicated mode to just adjust the master volume.

**Describe alternatives you've considered**
I'd like the screen to be just like the selection screen in app mode.

Volume     75
|========|

**Additional context**

**Comment by SchemingWeasels** [comment]
I suggest to have a shortcut to jump to master volume, and activating the shortcut again brings you back to the previous app.

If we reserve double click for mute, I'm not sure what other shortcut is available.

**Comment by t3knomanzer** [comment]
Quoting the reply in #78

“So the idea is to keep the input behavior consistent.
Long press to cycle between modes.
Tap to cycle between states within a mode, I.e: In app mode, switch between selection, and volume adjustment. In game mode switch between channel a, channel b selection and volume adjustment.
Double tap is a special action different for each mode. I.e: in game mode, it sets the volume of both apps to 50%. In app mode it controls mute/unmute.

Currently there is just app mode and game mode but that list will grow.”

With that in mind, it makes sense to have a dedicated Master volume mode. You can still control the master volume from App mode so you’re not forced to use it.
